build:
  stage: build
  image: debian:buster
  before_script:
    - apt-get -y update
    - apt-get -y install make dvdauthor genisoimage
  script:
    - make
  artifacts:
    name: "$CI_PROJECT_NAME-$CI_JOB_NAME-$CI_COMMIT_SHA"
    paths:
      - dvd.iso

deploy:itch:
  stage: deploy
  image: dosowisko/butler
  when: on_success
  retry: 2
  dependencies:
    - build
  only:
    refs:
      - master
    variables:
      - $BUTLER_TARGET
  environment:
    name: itch-$CI_JOB_NAME
    url: $ITCH_URL
  variables:
    GIT_STRATEGY: none
  script:
    - butler push dvd.iso $BUTLER_TARGET:ci --userversion `echo $CI_COMMIT_SHA | cut -c1-7`
